name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
init:
runs-on:unbuntu-latest
strategy:
matrix:
node-version:[17.x]
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name :String Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
      node-version : ${{matrix.node-version}}
      - name:intall modules
      run: npm install 
      - name:build projext
      run: npm run build 
